### ISSUE TITLE
[Player] - Build timer

### ISSUE THREAD

**Issue by Torfeltorfel** [Torfeltorfel/capstone-project#1]
### Value Preposition
**As a user,** 
**I want to** receive an acoustic feedback for the duration of my meditation, 
**so that** I don't have to double check the past time and break the meditation session

### Design
<img width="532" alt="Bildschirmfoto 2021-11-22 um 16 25 57" src="https://user-images.githubusercontent.com/71028924/142888358-47a6565d-ba7c-4e0f-985d-ff8d681eb84f.png">

### Acceptance criteria

- [x]  Let [users] start the meditation timer with a click on a button 
- [x]  Let [users] pause the meditation time with a click on a button
- [x]  The meditation time stops automatically after 15min
- [x] start and stop of the meditation comes with a {gong-sound}
- [x] only play sound when starting the meditation

### Out of Scope
- editing the duration of the time
- storing the time in the DB

### Tasks
- [x] Create a dedicated page
- [x] Create a player Component
- [x] find and install a sound package
- [x] find a gong sound

### Ressources
- gong-sound: https://freesound.org/people/InspectorJ/sounds/411090/
