### ISSUE TITLE
Success Modal

### ISSUE THREAD

**Issue by Torfeltorfel** [Torfeltorfel/capstone-project#15]
##Value Preposition
As a user I want to orient my self at the end of the meditation
so that I can take proper action without searching for them

##Design
![Bildschirmfoto 2021-11-29 um 09 35 14](https://user-images.githubusercontent.com/71028924/143834066-69756a31-f2fb-4b01-9ae7-c98970620634.png)

##Acceptance Criteria
- [ ] Show success overlay/modal after meditation
- [ ] Button leads the user back to the normal screen

##Tasks (for developers)
- Create feature branch
- [ ] Create feature branch for modal
- [ ] Build Modal component
- [ ] Build Button component
