### ISSUE TITLE
Feature/TimeSelector

### ISSUE THREAD

**Issue by Torfeltorfel** [Torfeltorfel/capstone-project#17]
##Value Preposition
As a user I want to select the meditation duration
so that I can decide, how long I want to meditate

##Design
![Bildschirmfoto 2021-11-29 um 09 51 27](https://user-images.githubusercontent.com/71028924/143836464-4c5b1ccf-da04-48d5-af01-2d9198caf2a7.png)

##Acceptance Criteria
- [ ] User can choose between different durations via scrolling
- [ ] durations are 1,2,4,5,10,15,20,25,30,35,40,50,60,70,80,90,100,120,140 Min
- [ ] default value is 15
- [x] Start meditation with defined duration with a click on a button

##Tasks (for developers)
- [x] Create feature branch
- [x] Create page with scroll functionality
- [x] Transfer duration to meditation player
