### ISSUE TITLE
Homescreen

### ISSUE THREAD

**Issue by Torfeltorfel** [Torfeltorfel/capstone-project#18]
##Value Preposition
As a user I want to easily orient myself when starting the app
so that I can view the pages quickly and without much effort

##Design
![Bildschirmfoto 2021-11-29 um 10 59 03](https://user-images.githubusercontent.com/71028924/143846919-1352df24-5c24-43d3-8bf6-94588d600b9a.png)

##Acceptance Criteria

- [ ]  All inputs are 'required'
- [ ] button should be disabled until title and amount are filled
- [ ] the user can access the home screen from the analytics page (button) & from the audio player (x button)

##Tasks (for developers)

- [ ] Create feature branch
- [ ] Add Readme
- [ ] List component
- [ ] add button on analytics page
- [ ] add button on audio player
