### ISSUE TITLE
Meditation Habit

### ISSUE THREAD

**Issue by Torfeltorfel** [Torfeltorfel/capstone-project#19]
##Value Preposition
As a user I want to be able to commit to a habit challenge. 

##Design

##Acceptance Criteria
- [ ] User can select between different challenges
- [ ] User gets redirected to the player

##Tasks (for developers)
- [ ] Show different challenge options
- [ ] Save challenge to localStorage
- [ ] Start meditation with pre-defined session duration
