### ISSUE TITLE
Feature - don't break the chain

### ISSUE THREAD

**Issue by Torfeltorfel** [Torfeltorfel/capstone-project#27]
##Value Preposition
As a user I want to see the progress on my challenge
so that I get motived to continue

##Design

##Acceptance Criteria

- [ ] A user should be able to activate a challenge
- [ ] A user should be able to continue a challenge
- [ ] A user should be able to view a chain of days, where she meditated
- [ ] A user should be able to stop/restart the challenge

##Tasks (for developers)

- Create feature branch
- [ ] List component
- ...
