### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by Torfeltorfel** [Torfeltorfel/capstone-project#28]
##Value Preposition
As a user I don't want that other users can proceed with my challenges
so that I can continue them on my own 

##Design
![Bildschirmfoto 2021-12-07 um 08 32 38](https://user-images.githubusercontent.com/71028924/144985840-58587461-7621-45ab-8b4c-26195dbfa7a2.png)
![Bildschirmfoto 2021-12-07 um 08 35 08](https://user-images.githubusercontent.com/71028924/144986158-b963795c-9b2e-45b9-abe5-1d253edb305d.png)

##Acceptance Criteria
- [ ] Username & password are required
- [ ] Restrict login, if username or password is wrong
- [ ] send error message, if password/login combination is wrong

### Nice to have
- [ ] toggle visibility of password when login in

##Tasks (for developers)
