### ISSUE TITLE
Challenge Success

### ISSUE THREAD

**Issue by Torfeltorfel** [Torfeltorfel/capstone-project#29]
### Value Preposition
As a user I want to get feedback on my challenge status
so that I can properly see the challenge status

### Acceptance Criteria
- [ ] User can start a challenge
- [ ] User should get feedback, if they have accomplished a challenge

#### Nice to Have
- [ ] Users should be able to view the challenge progress

##Tasks (for developers)
