### ISSUE TITLE
Add Database

### ISSUE THREAD

**Issue by Torfeltorfel** [Torfeltorfel/capstone-project#31]
### Value Preposition
As a user I want to have access to my data, even though I deleted the localStorage
so that I don't loose my progress

### Acceptance Criteria

- [ ] Get sessions for calendar from MongoDB
- [ ] Store session dates in MongoDB

### Tasks (for developers)

- [ ] Ramp up MongoDB
- [ ] read data from MongoDB
- [ ] save data in MongoDB
