### ISSUE TITLE
Add README file

### ISSUE THREAD

**Issue by Torfeltorfel** [Torfeltorfel/capstone-project#4]
##Value Preposition
As a developer/code reviewer I want to be able to fork the repository and make it run on my machine
so that I can review & test the project

##Tasks
- [ ] create a readme file which describes the basic of the project
- [ ] research about the different package-json script by asking the coaches
- [ ] add a manual for the different package-json scripts
- [ ] make the readme file compelling by using styles & icons
