### ISSUE TITLE
[Data Visualization] - Calendar

### ISSUE THREAD

**Issue by Torfeltorfel** [Torfeltorfel/capstone-project#8]
## Value Preposition
**As a user**
**I want to** I want to get visually nudged
**so that I am** pushed to keep up or build my habit

## Design
![Bildschirmfoto 2021-11-23 um 09 44 50](https://user-images.githubusercontent.com/71028924/142993683-c397c154-6108-40ea-bafe-86167dcf47ff.png)

### Must Have
- [x] When opening the page, the calendar shows the current month
- [x] Calendar shows days with and without accomplished meditation (accomplished = reached end of meditation)
- [x] Users can go from calendar view to meditation
- [x] Users can go from meditation to calendar view
- [x] Always set meditation timer to 0:00min after leaving the audio-player page

### Nice to Have
- [x] Users can switch the months in the calendar

## Room for discussion
- How much effort is it to build such a calendar?
- Is there another way to accomplish the habit goal without building a calendar?

## Tasks (for developers)
- [x] Create feature branch
- [x] Search for calendar package
- [x] Create component
- [x] Create analytics page
